#!/usr/bin/env bash
# configuration for an Ubuntu server:
#   - Localhost resolves to 127.0.0.2
#   - Mapping facebook.com to 8.8.8.8 in DNS

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
